CREATE DATABASE IF NOT EXISTS demoflyway;

USE demoflyway;


CREATE OR REPLACE TABLE CLIENTE (
	id INT NOT NULL AUTO_INCREMENT,
	nome VARCHAR(40) NOT NULL,
	email VARCHAR(20),
	PRIMARY KEY (id)
);

CREATE OR REPLACE TABLE ENDERECO (
	id INT NOT NULL AUTO_INCREMENT,
	rua VARCHAR(40) NOT NULL,
	bairro VARCHAR(20),
	cliente_id INT NOT NULL,
    FOREIGN KEY (cliente_id) REFERENCES CLIENTE(id) ON DELETE CASCADE,
	PRIMARY KEY (id)
);

CREATE OR REPLACE TABLE CATEGORIA (
    id INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(10),
    PRIMARY KEY (id)
);


CREATE OR REPLACE TABLE PRODUTO (
    id INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(20) NOT NULL UNIQUE,
    categoria_id INT NOT NULL,
    preco REAL NOT NULL,
    quantidade INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Quantidade disponivel do produto',
    PRIMARY KEY (id),
    FOREIGN KEY (categoria_id) REFERENCES CATEGORIA(id) ON DELETE CASCADE
);

CREATE OR REPLACE TABLE VENDA (
	id INT NOT NULL AUTO_INCREMENT,
	produto_id INT NOT NULL,
	cliente_id INT NOT NULL,
	quantidade INT NOT NULL,
    FOREIGN KEY (produto_id) REFERENCES PRODUTO(id) ON DELETE CASCADE,
    FOREIGN KEY (cliente_id) REFERENCES CLIENTE(id) ON DELETE CASCADE,
	hora TIME DEFAULT CURRENT_TIME,
	dia DATE DEFAULT CURRENT_DATE,
	PRIMARY KEY (id)
);


CREATE OR REPLACE TABLE REPOSICAO (
	id INT NOT NULL AUTO_INCREMENT,
	produto_id INT NOT NULL,
	data_reposicao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	FOREIGN KEY (produto_id) REFERENCES PRODUTO(id) ON DELETE CASCADE
);


CREATE OR REPLACE INDEX busca_por_nome_index ON PRODUTO (nome);

CREATE OR REPLACE INDEX busca_por_dia_index ON VENDA (dia);



CREATE OR REPLACE VIEW endereco_cliente AS
SELECT c.nome, e.rua, e.bairro
FROM CLIENTE c
JOIN ENDERECO e ON e.cliente_id = c.id;


DROP TEMPORARY TABLE IF EXISTS CONSOLIDADO_CLIENTE;
 
CREATE TEMPORARY TABLE CONSOLIDADO_CLIENTE(
  cliente_id INT DEFAULT NULL,
  total_compras REAL DEFAULT NULL,
  qtd_compras   REAL DEFAULT NULL
);



SELECT LAST_INSERT_ID();

SELECT ROW_COUNT();
